name: Node.js CI

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main, next, beta, '*.x' ]

  schedule:
    - cron: '0 2 * * *'

  workflow_dispatch: {}

jobs:
  Job:
    name: Node.js
    uses: artusjs/github-actions/.github/workflows/node-test.yml@master
    with:
      version: '8, 10, 12, 14.17.0, 14, 16, 18'
