name: CI

on:
  push:
    branches: [ master, 4.x ]

  pull_request:
    branches: [ master, 4.x ]

  workflow_dispatch: {}

jobs:
  Job:
    name: Node.js
    uses: artusjs/github-actions/.github/workflows/node-test.yml@v1
    with:
      version: '8, 10, 12, 14.17.0, 14, 16, 18'
